name: upload cadvisor
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cadvisor.yml'
jobs:
  upload_to_aliyun:
    name: 上传镜像到阿里云
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      -
        name: Log in to Aliyun Docker
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALY_DOCKER_USERNAME }}
          password: ${{ secrets.ALY_DOCKER_PASSWORD }}
      - name: Sync repository to ALY
        run: |
          docker pull google/cadvisor:latest
          docker tag google/cadvisor:latest registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKERHUB_USERNAME }}/cadvisor:latest
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKERHUB_USERNAME }}/cadvisor:latest