name: upload prometheusnet/docker_exporter
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker_exporter.yml'
jobs:
  upload_to_aliyun:
    name: 上传镜像到阿里云
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      -
        name: Log in to Aliyun Docker
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALY_DOCKER_USERNAME }}
          password: ${{ secrets.ALY_DOCKER_PASSWORD }}
      - name: Sync repository to ALY
        run: |
          docker pull prometheusnet/docker_exporter
          docker tag prometheusnet/docker_exporter registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKERHUB_USERNAME }}/docker_exporter
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKERHUB_USERNAME }}/docker_exporter