name: build logstash

on:
  push:
    branches:
      - main
    paths:
      - 'logstash/**'
jobs:
  deploy:
    name: 打包并上传
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./logstash
          file: ./logstash/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/logstash:8.5.3