name: build qinglong

on:
  push:
    branches:
      - main
    paths:
      - 'qinglong/**'
      - '.github/workflows/qinglong.yml'
jobs:
  deploy:
    name: 打包并上传python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./qinglong
          file: ./qinglong/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qinglong:latest
